name: Update Profile

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with Latest Data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Example step to fetch latest blog posts (using gautamkrishnar/blog-post-workflow)
      - name: Update latest blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://dev.to/feed/${{ github.repository_owner }},https://medium.com/feed/@${{ github.repository_owner }}"
          
      - name: WakaTime Readme
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: last_7_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: false
